// const API_BASE_URL = 'https://admin.inchbrick.com/api'
const API_BASE_URL = process.env.NODE_ENV === 'development' ? 'http://localhost:5000/api' : 'https://admin.inchbrick.com/api'
const API_URLS = {
  MEDIA_BASE: 'https://cdn.inchbrick.com',
  //  MEDIA_BASE: process.env.NODE_ENV === 'development' ? 'http://localhost:5000' : 'https://cdn.inchbrick.com',
  BANNER: `${API_BASE_URL}/banner`,
  PROPERTIES: `${API_BASE_URL}/properties`,
  PROPERTIESBYSLUG: (slug) => `${API_BASE_URL}/properties/${slug}`,
  PROPERTIES_CATEGORY: `${API_BASE_URL}/property-category`,
  PROPERTIES_AMENITIES: `${API_BASE_URL}/property-amenities`,
  PROPERTIES_TYPE: `${API_BASE_URL}/property-type`,
  PROPERTY_TYPE_SLUG: (slug) => `${API_BASE_URL}/property-type/${slug}`,
  PROPERTY_PRICE: `${API_BASE_URL}/property-price`,
  PROPERTY_FILE: `${API_BASE_URL}/property-file`,
  BLOG_TAG: `${API_BASE_URL}/blog-tags`,
  BLOG_TAG_SLUG: (slug) => `${API_BASE_URL}/blog-tags/${slug}`,
  BLOG: `${API_BASE_URL}/blog`,
  BLOGSLUG: (slug) => `${API_BASE_URL}/blog/${slug}`,
  BLOGCATEGORY: `${API_BASE_URL}/blog-category`,
  BLOGCATEGORYSLUG: (slug) => `${API_BASE_URL}/blog-category/${slug}`,
  META: `${API_BASE_URL}/meta`,
  METABYSLUG: (slug) => `${API_BASE_URL}/meta/${slug}`,
  AGENT: `${API_BASE_URL}/admin-register`,
  AGENTSLUG: (slug) => `${API_BASE_URL}/admin-register/${slug}`,
  DEVELOPER: `${API_BASE_URL}/developer`,
  DEVELOPERSLUG: (slug) => `${API_BASE_URL}/developer/${slug}`,
  LOCATION: `${API_BASE_URL}/city`,
  LOCATIONSLUG: (slug) => `${API_BASE_URL}/city/${slug}`,
  SITES: `${API_BASE_URL}/site-setting`,
  CONTACT: `${API_BASE_URL}/contact`,
  EXPO: `${API_BASE_URL}/expo`,
  TRIGGER: `${API_BASE_URL}/trigger`,
  REVIEW_DATA: `${API_BASE_URL}/review`,
  COMMENT: `${API_BASE_URL}/comment`,
  USER: `${API_BASE_URL}/user-login`,
  REGISTER_USER: `${API_BASE_URL}/user-register`,
  REGISTER_USER_SLUG: (slug) => `${API_BASE_URL}/user-register/${slug}`,
  FORGET: `${API_BASE_URL}/user-forget`,
  VALID_OTP: `${API_BASE_URL}/user-valid-otp`,
  PASS_RESET: `${API_BASE_URL}/reset-password`,
  NEW_VISITOR: `${API_BASE_URL}/new-visitor`,
  UNIQUE_USER: `https://ipapi.co/json`,
  TERMS: `${API_BASE_URL}/terms`,
  FAQ: `${API_BASE_URL}/faq`,
  POPUP: `${API_BASE_URL}/popup`,
  INQUIRYMCQ: `${API_BASE_URL}/inquiry-manager`,
  INQUIRY: `${API_BASE_URL}/inquiry`,
  CURRENCY: (slug) => `https://api.exchangerate-api.com/v4/latest/${slug}`,
  CAREER: `${API_BASE_URL}/resume`,
  MANAGE_CAREER: `${API_BASE_URL}/manage-career`,
  MANAGE_CAREER_SLUG: (slug) => `${API_BASE_URL}/manage-career/${slug}`,
  PRESS: `${API_BASE_URL}/press-release`,
  DOCUMENTS: `${API_BASE_URL}/document`,
  DOCUMENTS_SLUG: (slug) => `${API_BASE_URL}/document/${slug}`,
  WEBSITEPAGE: `${API_BASE_URL}/website-page`,
  TOURISM: `${API_BASE_URL}/tourism`,
  TOURISMFILE: `${API_BASE_URL}/tourism-file`,
  EVENTDETAILS: `${API_BASE_URL}/event-details`,
  EVENTDETAILS_SLUG: (slug) => `${API_BASE_URL}/event-details/${slug}`,
  EVENTFILE: `${API_BASE_URL}/event-file`,
  OFFERS: `${API_BASE_URL}/offers`,
  EVENTPAGE: `${API_BASE_URL}/event-page`,
  INSTA_GALLERY: `${API_BASE_URL}/insta-gallery`,
  REVIEW_GALLERY: `${API_BASE_URL}/review-gallery`,
  SEO_LINKS: `${API_BASE_URL}/seo-links`,
};

module.exports = API_URLS;